[package]
name = "consensus"
version = "1.0.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
bincode = "1.3"

log = "*"
log4rs = { version = "*", features = ["gzip"] }
cita-types = { git = "https://github.com/cita-cloud/cita-types",branch = "main" }
cita-crypto = { git = "https://github.com/cita-cloud/cita-crypto",branch = "main" }
cita-hashable = { git = "https://github.com/cita-cloud/hashable",branch = "main" }
time = "0.1.36"
lru-cache = "0.1"
rustc-hex = "1.0"
min-max-heap = "1.2.2"
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto", branch = "wip-7.0.0-dev" }
tonic = "*"
prost = "*"
tokio = { version = "*", features = ["full"] }
protobuf = { version = "*", features = ["with-bytes"] }
crossbeam = "0.8.1"
anyhow = "*"
toml = "0.5"
clap = "3.0.0-beta.2"
git-version = "*"
crc32fast = "1.2.1"
status_code = { git = "https://github.com/cita-cloud/status_code", branch = "main"}
backtrace = "0.3"
arrayref = "0.3"


[features]
default = ["sm2", "sm3hash"]
secp256k1 = ["cita-crypto/secp256k1"]
ed25519 = ["cita-crypto/ed25519"]
sm2 = ["cita-crypto/sm2"]
sha3hash = ["cita-hashable/sha3hash"]
blake2bhash = ["cita-hashable/blake2bhash"]
sm3hash = ["cita-hashable/sm3hash"]

[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1
