[package]
name = "consensus"
version = "6.3.1-alpha.1"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
bincode = "1.3"

log = "0.4.14"
log4rs = { version = "1.0", features = ["gzip"] }
cita-types = "0.1"
time = "0.1"
lru-cache = "0.1"
rustc-hex = "1.0"
min-max-heap = "1.2"
hex = "0.4"

cloud-util = { git = "https://github.com/cita-cloud/cloud-util.git" }
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto.git" }
status_code = { package = "cloud-code", git = "https://github.com/cita-cloud/status_code.git" }

tonic = "0.5"
prost = "0.8"
tokio = { version = "1.0", features = ["full"] }
crossbeam = "0.8"
anyhow = "1.0"
toml = "0.5"
clap = { version = "3.0.14", features = ["derive"] }
git-version = "0.3"
crc32fast = "1.2"
backtrace = "0.3"
arrayref = "0.3"
async-recursion = "0.3.2"

[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1
