[package]
name = "consensus"
version = "1.0.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
dotenv = "0.13.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
bincode = "1.3"

log = "*"
log4rs = { version = "*", features = ["gzip"] }
util = { git = "https://github.com/citahub/cita-common.git", branch = "develop" }
cita-types = { git = "https://github.com/citahub/cita-common.git", branch = "develop" }

ethereum-types = "0.11.0"
cita-crypto = { git = "https://github.com/citahub/cita-common.git", branch = "develop" }
hashable = { git = "https://github.com/citahub/cita-common.git", branch = "develop" }
cita-directories = { git = "https://github.com/citahub/cita-common.git", branch = "develop" }
proof = { git = "https://github.com/citahub/cita-common.git", branch = "develop" }
time = "0.1.36"
engine = { git = "https://github.com/citahub/cita-common.git", branch = "develop" }
lru-cache = "0.1"
authority_manage = { git = "https://github.com/citahub/cita-common.git", branch = "develop" }
rustc-hex = "1.0"
min-max-heap = "1.2.2"
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto.git", branch = "full_block_develop" }
tonic = "*"
prost = "*"
tokio = { version = "*", features = ["full"] }
protobuf = { version = "*", features = ["with-bytes"] }
crossbeam = "*"
anyhow = "*"
toml = "0.5"
clap = "3.0.0-beta.2"
git-version = "*"
crc32fast = "1.2.1"

[build-dependencies]
util = { git = "https://github.com/citahub/cita-common.git", branch = "develop" }


[features]
default = ["sm2", "sm3hash"]
secp256k1 = ["cita-crypto/secp256k1", "proof/secp256k1","engine/secp256k1"]
ed25519 = ["cita-crypto/ed25519", "proof/ed25519", "engine/ed25519"]
sm2 = ["cita-crypto/sm2", "proof/sm2", "engine/sm2"]
sha3hash = ["hashable/sha3hash",  "proof/sha3hash", "engine/sha3hash"]
blake2bhash = ["hashable/blake2bhash", "proof/blake2bhash", "engine/blake2bhash"]
sm3hash = ["hashable/sm3hash", "proof/sm3hash", "engine/sm3hash"]


[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1
